name: CI

on:
  push:
    paths:
      - '**.f90'
      - '**.yml'

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: '10'}
          - {compiler: gcc, version: 'latest'}
          - {compiler: intel, version: '2024.1'}
          - {compiler: intel, version: 'latest'}
          #~ - {compiler: nvidia-hpc, version: 'latest'}
          - {compiler: lfortran, version: '0.66.0'}
          #~ - {compiler: aocc, version: 'latest'}
        exclude:
          #~ - os: macos-latest
            #~ toolchain: {compiler: nvidia-hpc}
          #~ - os: macos-latest
            #~ toolchain: {compiler: aocc}
          #~ - os: macos-latest
            #~ toolchain: {compiler: intel}
          #~ - os: macos-latest
            #~ toolchain: {compiler: gcc, version: '10'}
          - os: windows-latest
            toolchain: {compiler: intel}
          - os: windows-latest
            toolchain: {compiler: gcc, version: '10'}
          - os: windows-latest
            toolchain: {compiler: lfortran}
    steps:
      - uses: actions/checkout@v7
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: 'current'
      #~ - name: Install Reference BLAS
        #~ run: sudo apt-get update && sudo apt-get install -y libblas-dev liblapack-dev
        #~ if: runner.os == 'Linux'
      - name: Run tests
        run: |
          fpm test --compiler ${{ env.FC }} 
